# Generated by Django 3.0.6 on 2021-03-10 02:36

from django.db import migrations, models
import utsapi.models


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to=utsapi.models.get_upload_path),
        ),
    ]
