# Generated by Django 3.0.6 on 2020-11-02 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
