# Generated by Django 3.0.6 on 2021-02-01 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0002_auto_20210118_0028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
        migrations.CreateModel(
            name='FileDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField(null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utsapi.File')),
            ],
        ),
    ]
