# Generated by Django 3.0.6 on 2021-04-05 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0002_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utsapi.Project'),
        ),
        migrations.AlterField(
            model_name='filedownload',
            name='download_date',
            field=models.DateTimeField(default='2020-01-01'),
            preserve_default=False,
        ),
    ]
