# Generated by Django 3.0.6 on 2021-04-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0003_auto_20210405_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.TextField(blank=True, null=True),
        ),
    ]
