# Generated by Django 3.0.6 on 2020-11-02 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0003_delete_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
