# Generated by Django 3.0.6 on 2021-04-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utsapi', '0004_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.TextField(blank=True, default='es', null=True),
        ),
    ]
